<!--create by Anton 2015-08-05 -->

<div class="container profile top">
    <div class="jumbotron profile">
        <img class="img-rounded avatar" src="/img/no_avatar.jpg" alt="avatar">
        <div class="description-block">
            <div class="last-name"><?=$user;?></div>
            <div class="telephon">Телефон: +3 (090) 567-32-44</div>
            <div class="telephon">Ставки:></div>
            <div class="telephon">Лоты: </div>
        </div>


        <hr>
        <div class="text-center">
            <a href="/user/create" class="btn btn-info">Добавить лот</a> | <a href="/user/mylots" class="btn btn-info">Мои лоты</a> | <a  href="/user/mybids" class="btn btn-info">Мои ставки</a> | <a href="/user/settings" class="btn btn-info">Настройки</a>
        </div>

        <hr>
        <form role="form" class="form container" id="searchGoodsForm">
            <div class="form-group">
                <div class="col-sm-2 label-fix"> Сортировка по</div>
                <div class="col-sm-4">
                    <select name="sortGoods" class="form-control">
                        <option value="1">цене (убывание)</option>
                        <option value="2">цене (возрастание)</option>
                        <option value="3">дате добавления</option>
                    </select>
                </div>
                <div class="col-sm-4">
                    <input name="searchText" type="text" class="form-control" placeholder="Введите ключевое слово для поиска">
                </div>
                <div class="col-sm-2">
                    <input class="btn btn-info" type="submit" value="Поиск">
                </div>
            </div><!-- /input-group -->
        </form>
    </div>
</div>

<div class="container profile">
    <div class="jumbotron profile">
        <div class="text-center"><h2>Мои ставки</h2></div class="text-center">
        <div class="well">

            <?php foreach($bids as $bid) { ?>
                <div class="lot-block">
                    <div class="panel-heading">
                        <h3 class="panel-title"><a href="/goods/description?id=<?=$bid["id"]?>"><?=$bid["title"];?></a></h3>
                    </div>
                    <div class="panel-body">
                        <img class="lot-photo" src="/img/goods-desc.png">
                        <?=$bid["description"];?>
                        <ul class="list-unstyled">
                            <li><a href="#"><span class="glyphicon glyphicon-usd"></span> <?=$bid["current_price"];?></a></li>
                        </ul>
                    </div>
                </div>
            <?php } ?>
        </div>

        <!--++Блок paginator++-->
        <div class="paginator">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <ul class="pagination">
                        <li><a href="#">&laquo;</a></li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">&raquo;</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!--++Блок paginator++-->
    </div>
</div>