<div class="container-fluid profile">
<div class="row-fluid">
<div class="col-lg-2">
    <!--Sidebar content-->
    <img class="img-rounded" src="/img/no_avatar.jpg" alt="avatar">

    <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/user/mylots">Лоты<span class="badge pull-right">10</span></a></li>
        <li><a href="/user/mybids">Аукционы<span class="badge pull-right">7</span></a></li>
        <li><a href="/user/settings">Настройки</a></li>
    </ul>
</div>
        <div class="col-lg-10">
            <ul class="nav nav-pills">
                <li class="active"><a href="/goods/create">Добавить лот</a></li>

                <li class="dropdown">
                    <a class="dropdown-toggle"
                       data-toggle="dropdown"
                       href="#">
                        Сортировка
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- links -->
                        <li><a href="">по возрастанию цен</a></li>
                        <li><a href="">по убыванию цен</a></li>
                        <li><a href="">по оценке</a></li>
                        <li><a href="">по новизне</a></li>
                    </ul>
                </li>

                <li>
                    <input required="" type="search" class="form-control" placeholder="Поиск ...">
                </li>
            </ul>

            <div class="row  well">

                <div class="col-sm-3">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title"><a href="index.php?action=goods_description">Название лота (ссылка)</a></h3>
                        </div>
                        <div class="panel-body">
                            <img class="img-rounded" src="/img/goods-desc.png">
                            <p class="text-justify">Краткое описание лота<br> Short description of goods <br>Краткое описание лота<br> Short description of goods </p>
                            <ul class="list-unstyled">
                                <li><a href="mailto:mail@example.com"><span class="glyphicon glyphicon-envelope"></span> mail продавца</a></li>
                                <li><a href="tel:77777777"><span class="glyphicon glyphicon-phone"></span> 77777777</a></li>
                                <li><a href="#"><span class="glyphicon glyphicon-usd"></span> Последняя ставка</a></li>
                            </ul>
                            <div class="form-group has-feedback">
                                <span class="glyphicon glyphicon-tags form-control-feedback"></span>
                                <input type="button" class="form-control btn btn-info" value="Редактировать" data-toggle="modal" data-target="#makeBidModal">
                                <input type="button" class="form-control btn btn-danger" value="Удалить" data-toggle="modal" data-target="#makeBidModal">
                            </div>
                        </div>
                    </div>
                </div><!-- /.col-sm-4 -->

                <div class="col-sm-3">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title"><a href="index.php?action=goods_description">Название лота (ссылка)</a></h3>
                        </div>
                        <div class="panel-body">
                            <img class="img-rounded" src="/img/goods-desc.png">
                            <p class="text-justify">Краткое описание лота<br> Short description of goods <br>Краткое описание лота<br> Short description of goods </p>
                            <ul class="list-unstyled">
                                <li><a href="mailto:mail@example.com"><span class="glyphicon glyphicon-envelope"></span> mail продавца</a></li>
                                <li><a href="tel:77777777"><span class="glyphicon glyphicon-phone"></span> 77777777</a></li>
                                <li><a href="#"><span class="glyphicon glyphicon-usd"></span> Последняя ставка</a></li>
                            </ul>
                            <div class="form-group has-feedback">
                                <span class="glyphicon glyphicon-tags form-control-feedback"></span>
                                <input type="button" class="form-control btn btn-info" value="Редактировать" data-toggle="modal" data-target="#makeBidModal">
                                <input type="button" class="form-control btn btn-danger" value="Удалить" data-toggle="modal" data-target="#makeBidModal">
                            </div>
                        </div>
                    </div>
                </div><!-- /.col-sm-4 -->

                <div class="col-sm-3">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title"><a href="index.php?action=goods_description">Название лота (ссылка)</a></h3>
                        </div>
                        <div class="panel-body">
                            <img class="img-rounded" src="/img/goods-desc.png">
                            <p class="text-justify">Краткое описание лота<br> Short description of goods <br>Краткое описание лота<br> Short description of goods </p>
                            <ul class="list-unstyled">
                                <li><a href="mailto:mail@example.com"><span class="glyphicon glyphicon-envelope"></span> mail продавца</a></li>
                                <li><a href="tel:77777777"><span class="glyphicon glyphicon-phone"></span> 77777777</a></li>
                                <li><a href="#"><span class="glyphicon glyphicon-usd"></span> Последняя ставка</a></li>
                            </ul>
                            <div class="form-group has-feedback">
                                <span class="glyphicon glyphicon-tags form-control-feedback"></span>
                                <input type="button" class="form-control btn btn-info" value="Редактировать" data-toggle="modal" data-target="#makeBidModal">
                                <input type="button" class="form-control btn btn-danger" value="Удалить" data-toggle="modal" data-target="#makeBidModal">
                            </div>
                        </div>
                    </div>
                </div><!-- /.col-sm-4 -->

                <div class="col-sm-3">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title"><a href="index.php?action=goods_description">Название лота (ссылка)</a></h3>
                        </div>
                        <div class="panel-body">
                            <img class="img-rounded" src="/img/goods-desc.png">
                            <p class="text-justify">Краткое описание лота<br> Short description of goods <br>Краткое описание лота<br> Short description of goods </p>
                            <ul class="list-unstyled">
                                <li><a href="mailto:mail@example.com"><span class="glyphicon glyphicon-envelope"></span> mail продавца</a></li>
                                <li><a href="tel:77777777"><span class="glyphicon glyphicon-phone"></span> 77777777</a></li>
                                <li><a href="#"><span class="glyphicon glyphicon-usd"></span> Последняя ставка</a></li>
                            </ul>
                            <div class="form-group has-feedback">
                                <span class="glyphicon glyphicon-tags form-control-feedback"></span>
                                <input type="button" class="form-control btn btn-info" value="Редактировать" data-toggle="modal" data-target="#makeBidModal">
                                <input type="button" class="form-control btn btn-danger" value="Удалить" data-toggle="modal" data-target="#makeBidModal">
                            </div>
                        </div>
                    </div>
                </div><!-- /.col-sm-4 -->

                <div class="col-sm-3">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title"><a href="index.php?action=goods_description">Название лота (ссылка)</a></h3>
                        </div>
                        <div class="panel-body">
                            <img class="img-rounded" src="/img/goods-desc.png">
                            <p class="text-justify">Краткое описание лота<br> Short description of goods <br>Краткое описание лота<br> Short description of goods </p>
                            <ul class="list-unstyled">
                                <li><a href="mailto:mail@example.com"><span class="glyphicon glyphicon-envelope"></span> mail продавца</a></li>
                                <li><a href="tel:77777777"><span class="glyphicon glyphicon-phone"></span> 77777777</a></li>
                                <li><a href="#"><span class="glyphicon glyphicon-usd"></span> Последняя ставка</a></li>
                            </ul>
                            <div class="form-group has-feedback">
                                <span class="glyphicon glyphicon-tags form-control-feedback"></span>
                                <input type="button" class="form-control btn btn-info" value="Редактировать" data-toggle="modal" data-target="#makeBidModal">
                                <input type="button" class="form-control btn btn-danger" value="Удалить" data-toggle="modal" data-target="#makeBidModal">
                            </div>
                        </div>
                    </div>
                </div><!-- /.col-sm-4 -->

                <div class="col-sm-3">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title"><a href="index.php?action=goods_description">Название лота (ссылка)</a></h3>
                        </div>
                        <div class="panel-body">
                            <img class="img-rounded" src="/img/goods-desc.png">
                            <p class="text-justify">Краткое описание лота<br> Short description of goods <br>Краткое описание лота<br> Short description of goods </p>
                            <ul class="list-unstyled">
                                <li><a href="mailto:mail@example.com"><span class="glyphicon glyphicon-envelope"></span> mail продавца</a></li>
                                <li><a href="tel:77777777"><span class="glyphicon glyphicon-phone"></span> 77777777</a></li>
                                <li><a href="#"><span class="glyphicon glyphicon-usd"></span> Последняя ставка</a></li>
                            </ul>
                            <div class="form-group has-feedback">
                                <span class="glyphicon glyphicon-tags form-control-feedback"></span>
                                <input type="button" class="form-control btn btn-info" value="Редактировать" data-toggle="modal" data-target="#makeBidModal">
                                <input type="button" class="form-control btn btn-danger" value="Удалить" data-toggle="modal" data-target="#makeBidModal">
                            </div>
                        </div>
                    </div>
                </div><!-- /.col-sm-4 -->

                <div class="col-sm-3">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title"><a href="index.php?action=goods_description">Название лота (ссылка)</a></h3>
                        </div>
                        <div class="panel-body">
                            <img class="img-rounded" src="/img/goods-desc.png">
                            <p class="text-justify">Краткое описание лота<br> Short description of goods <br>Краткое описание лота<br> Short description of goods </p>
                            <ul class="list-unstyled">
                                <li><a href="mailto:mail@example.com"><span class="glyphicon glyphicon-envelope"></span> mail продавца</a></li>
                                <li><a href="tel:77777777"><span class="glyphicon glyphicon-phone"></span> 77777777</a></li>
                                <li><a href="#"><span class="glyphicon glyphicon-usd"></span> Последняя ставка</a></li>
                            </ul>
                            <div class="form-group has-feedback">
                                <span class="glyphicon glyphicon-tags form-control-feedback"></span>
                                <input type="button" class="form-control btn btn-info" value="Редактировать" data-toggle="modal" data-target="#makeBidModal">
                                <input type="button" class="form-control btn btn-danger" value="Удалить" data-toggle="modal" data-target="#makeBidModal">
                            </div>
                        </div>
                    </div>
                </div><!-- /.col-sm-4 -->

                <div class="col-sm-3">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title"><a href="index.php?action=goods_description">Название лота (ссылка)</a></h3>
                        </div>
                        <div class="panel-body">
                            <img class="img-rounded" src="/img/goods-desc.png">
                            <p class="text-justify">Краткое описание лота<br> Short description of goods <br>Краткое описание лота<br> Short description of goods </p>
                            <ul class="list-unstyled">
                                <li><a href="mailto:mail@example.com"><span class="glyphicon glyphicon-envelope"></span> mail продавца</a></li>
                                <li><a href="tel:77777777"><span class="glyphicon glyphicon-phone"></span> 77777777</a></li>
                                <li><a href="#"><span class="glyphicon glyphicon-usd"></span> Последняя ставка</a></li>
                            </ul>
                            <div class="form-group has-feedback">
                                <span class="glyphicon glyphicon-tags form-control-feedback"></span>
                                <input type="button" class="form-control btn btn-info" value="Редактировать" data-toggle="modal" data-target="#makeBidModal">
                                <input type="button" class="form-control btn btn-danger" value="Удалить" data-toggle="modal" data-target="#makeBidModal">
                            </div>
                        </div>
                    </div>
                </div><!-- /.col-sm-4 -->

                <div class="col-sm-3">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title"><a href="index.php?action=goods_description">Название лота (ссылка)</a></h3>
                        </div>
                        <div class="panel-body">
                            <img class="img-rounded" src="/img/goods-desc.png">
                            <p class="text-justify">Краткое описание лота<br> Short description of goods <br>Краткое описание лота<br> Short description of goods </p>
                            <ul class="list-unstyled">
                                <li><a href="mailto:mail@example.com"><span class="glyphicon glyphicon-envelope"></span> mail продавца</a></li>
                                <li><a href="tel:77777777"><span class="glyphicon glyphicon-phone"></span> 77777777</a></li>
                                <li><a href="#"><span class="glyphicon glyphicon-usd"></span> Последняя ставка</a></li>
                            </ul>
                            <div class="form-group has-feedback">
                                <span class="glyphicon glyphicon-tags form-control-feedback"></span>
                                <input type="button" class="form-control btn btn-info" value="Редактировать" data-toggle="modal" data-target="#makeBidModal">
                                <input type="button" class="form-control btn btn-danger" value="Удалить" data-toggle="modal" data-target="#makeBidModal">
                            </div>
                        </div>
                    </div>
                </div><!-- /.col-sm-4 -->
            </div>
            <!-- //////////////////////////////////////////////////////////////////////////////////////////-->
            <!-- PAGINATION -->
            <div class="pull-left">
                <ul class="pagination">
                    <li class="previous disabled"><a href="#">&lt;</a></li>
                </ul>
                <ul class="pagination">
                    <li class="active"><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                </ul>
                <ul class="pagination">
                    <li class="next"><a href="#">&gt;</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
