<!--create by Anton 2015-08-05 -->

<div class="container profile top">
    <div class="jumbotron profile">
        <img class="img-rounded avatar" src="/img/no_avatar.jpg" alt="avatar">
        <div class="description-block">
            <div class="last-name"><?=$user;?></div>
            <div class="telephon">Телефон: +3 (090) 567-32-44</div>
            <div class="telephon">Ставки: </div>
            <div class="telephon">Лоты: </div>

        </div>


        <hr>
        <div style="text-align: center">
            <a href="/user/create" class="btn btn-info">Добавить лот</a> | <a href="/user/mylots" class="btn btn-info">Мои лоты</a> | <a  href="/user/mybids" class="btn btn-info">Мои ставки</a> | <a href="/user/settings" class="btn btn-info">Настройки</a>
        </div>

        <hr>
        <form role="form" class="form container" id="searchGoodsForm">
            <div class="form-group">
                <div class="col-sm-2 label-fix"> Сортировка по</div>
                <div class="col-sm-4">
                    <select name="sortGoods" class="form-control">
                        <option value="1">цене (убывание)</option>
                        <option value="2">цене (возрастание)</option>
                        <option value="3">дате добавления</option>
                    </select>
                </div>
                <div class="col-sm-4">
                    <input name="searchText" type="text" class="form-control" placeholder="Введите ключевое слово для поиска">
                </div>
                <div class="col-sm-2">
                    <input class="btn btn-info" type="submit" value="Поиск">
                </div>
            </div><!-- /input-group -->
        </form>
    </div>
</div>

<div class="container profile">
    <div class="jumbotron profile">

        <div class="row  well">
            <?php
            if (count($products) > 0) {
                foreach ($products as $key => $product) { ?>


                    <div class="lot-block">
                        <div class="panel-heading">
                            <h3 class="panel-title"><a href="/goods/description?id=<?=$product["id"];?>"><?=$product["title"];?></a></h3>
                        </div>
                        <div class="panel-body">
                            <img class="lot-photo" src="/img/goods-desc.png">
                            <?=$product["description"];?>
                            <ul class="list-unstyled">
                                <li><a href="#"><span class="glyphicon glyphicon-usd"></span> <?=$product["current_price"]?></a></li>
                            </ul>
                            <div class="form-group has-feedback">
                                <span class="glyphicon glyphicon-tags form-control-feedback"></span>
                                <input type="button" class="form-control btn btn-info" value="Редактировать" data-toggle="modal" data-target="#makeBidModal">
                                <input type="button" class="form-control btn btn-danger" value="Удалить" data-toggle="modal" data-target="#makeBidModal">
                            </div>
                        </div>
                    </div>
                <?php } } ?>
        </div>

        <!--++Блок paginator++-->
        <div class="paginator">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <ul class="pagination">
                        <li><a href="#">&laquo;</a></li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">&raquo;</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!--++Блок paginator++-->
    </div>
</div>