<!-- created by Kit-Kat1 and Anton Ambrosimov -->
<!-- modified by Sebastian
add bootstrap-design classes to input fields
add names and id`s, inputs group by forms
table style of page deleted -->
<?php //if (!$settings) App::redirect('/user/notfound'); ?>

<div class="container profile top">
    <div class="jumbotron profile">
        <img class="img-rounded avatar" src="/img/no_avatar.jpg" alt="avatar">
        <div class="description-block">
            <div class="last-name"><?=$user;?></div>
            <div class="telephon">Телефон: +3 (090) 567-32-44</div>
            <div class="telephon">Ставки: </div>
            <div class="telephon">Лоты: </div>
        </div>
        <hr>
        <div style="text-align: center">
            <a href="/user/create" class="btn btn-info">Добавить лот</a> | <a href="/user/mylots" class="btn btn-info">Мои лоты</a> | <a  href="/user/mybids" class="btn btn-info">Мои ставки</a> | <a href="/user/settings" class="btn btn-info">Настройки</a>
        </div>
    </div>
</div>
        <!-- Sidebar content (menu) -->
        <!-- Main content -->

<div class="container profile">
    <div class="jumbotron profile">
                <!--Password settings-->
                <div class="prof_settings">
                    <h3>Изменить пароль</h3>
                    <form action="" method="post" id="changePasswordSettings">
                        <input class="form-control form-group" type="password" placeholder="Старый пароль" required name="userOldPassword">
                        <input class="form-control form-group" type="password" placeholder="Новый пароль" required name="userNewPassword">
                        <input class="form-control form-group" type="password" placeholder="Повторите пароль" required  name="userNewPasswordAgain">
                        <input type="hidden" name="action" value="password">
                        <div class="form-group">
                            <input class="btn btn-info" type="submit" value="Изменить пароль">    
                        </div>
                    </form>
                </div>

                <!--Email settings-->
                <div class="prof_settings">
                    <h3>Изменить email</h3>
                    <form action="" method="post" id="changeEmailSettings">
                        <input class="form-control form-group" type="email" placeholder="Старый Email" name="userOldEmail">
                        <input class="form-control form-group" type="email" placeholder="Новый Email" name="userNewEmail">
                        <input type="hidden" name="action" value="email" >
                        <div class="form-group">
                            <input class="btn btn-info" type="submit" value="Изменить email">
                        </div>
                    </form>
                </div>

                <!--SelfData Settings-->
                <div class="prof_settings">
                    <h3>Личные данные</h3>
                    <form action="" method="post" id="changeSelfSettings">
                        <input class="form-control form-group" type="text" placeholder="Фамилия"  name="userNewSurname">
                        <input class="form-control form-group" type="text" placeholder="Имя"  name="userNewName">
                        <input name="userNewTel" id="userNewTel" required type="tel" class="form-control form-group" placeholder="Телефон в формате +380 (ХХ) ХХ ХХ ХХХ">
                        <input type="hidden" name="action" value="profile" >
                        <div class="form-group">
                            <input class="btn btn-info" type="submit" value="Изменить данные">
                        </div>
                    </form>
                </div>

     </div>
</div>
