<!-- Carousel
    ================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="item active">
            <img src="/img/slider/slide-1.jpg" alt="First slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>BAZAR</h1>
                    <p>Купи мечту дешевле!</p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="/img/slider/slide-2.jpg" alt="Second slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Заголовок 2</h1>
                    <p>Описание второго рекламного баннера.</p>
                    <p><a class="btn btn-lg btn-primary" href="<?=$url?>/goods/search?cat=2" role="button">Скидки в категории 2!</a></p>
                </div>
            </div>
        </div>
        <div class="item">
            <img src="/img/slider/slide-3.jpg" alt="Third slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Заголовок 3</h1>
                    <p>Описание 3 рекламного баннера.</p>
                </div>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div><!-- /.carousel -->

<div class="container theme-showcase" role="main">
    <!-- //////////////////////////////////////////////////////////////////////////////////////////-->
    <div class="page-header">
        <h1 class="text-center">Все товары</h1>
    </div>
    <div class="row  well">
        <?php foreach ($lastGoods as $product) :?>
            <div class="col-sm-4">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title"><a href="<?=$url?>/goods/description?id=<?= $product['id']?>"><?= $product['title']?></a></h3>
                    </div>
                    <div class="panel-body">
                        <img class="img-rounded" src="/img/goods-desc.png">
                        <p class="text-justify"><?= $product['description']?></p>
                        <ul class="list-unstyled">
                            <li><a href="mailto:<?= $product['email']?>"><span class="glyphicon glyphicon-envelope"></span> Связаться с продавцом</a></li>
                            <li><a href="tel:<?= $product['phone']?>"><span class="glyphicon glyphicon-phone"></span> <?= $product['phone']?></a></li>
                            <li><p><span class="glyphicon glyphicon-usd"></span> Последняя ставка</p></li>
                        </ul>
                        <div class="form-group has-feedback">
                            <span class="glyphicon glyphicon-tags form-control-feedback"></span>
                            <input type="button" class="form-control btn btn-success" value="Сделать ставку" data-toggle="modal" data-target="#makeBidModal">
                        </div>
                    </div>
                </div>
            </div><!-- /.col-sm-4 -->
        <?php endforeach; ?>
        <!-- //////////////////////////////////////////////////////////////////////////////////////////-->

    </div>
    <!-- PAGINATION -->
    <div class="pull-right">
        <ul class="pagination">
            <li class="previous disabled"><a href="#"><</a></li>
        </ul>
        <ul class="pagination">
            <li class="active"><a href="#">1</a></li>
            <li><a href="/page/index?page=2">2</a></li>
            <li><a href="/page/index?page=3">3</a></li>
            <li><a href="/page/index?page=4">4</a></li>
            <li><a href="/page/index?page=5">5</a></li>
        </ul>
        <ul class="pagination">
            <li class="next"><a href="#">></a></li>
        </ul>
    </div>
    <!-- PRESENT TYPE -->
    <!--<div class="btn-group pull-left" data-toggle="buttons">
      <label class="btn btn-default">
              <input type="radio" name="options" id="option1">
              <span class="glyphicon glyphicon-th"></span>	Таблица
            </label>
      <label class="btn btn-default">
              <input type="radio" name="options" id="option2">
              <span class="glyphicon glyphicon-th-list"></span>	Список
            </label>
    </div>-->



    <!-- Modal СДЕЛАТЬ СТАВКУ-->
    <div class="modal fade" id="makeBidModal" tabindex="-1" role="dialog" aria-labelledby="makeBidModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Осуществить ставку на лот //выбранный лот//</h4>
                </div>
                <div class="modal-body">

                    <ul class="list-unstyled">

                        <div class="list-group">
                            <a href="#" class="list-group-item">
                                <h4 class="list-group-item-heading">Ставка</h4>
                                <p class="list-group-item-text">Кто поставил</p>
                                <a href="#" class="list-group-item">
                                    <h4 class="list-group-item-heading">Ставка</h4>
                                    <p class="list-group-item-text">Кто поставил</p>
                                    <a href="#" class="list-group-item">
                                        <h4 class="list-group-item-heading">Ставка</h4>
                                        <p class="list-group-item-text">Кто поставил</p>
                                    </a>
                                    <a href="#" class="list-group-item active">
                                        <h4 class="list-group-item-heading">Последняя ставка</h4>
                                        <p class="list-group-item-text">Кто поставил</p>
                                    </a>
                        </div>
                    </ul>
                    <form class="form-horizontal" role="form">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Ваша ставка </label>
                            <div class="col-sm-10">
                                <input required type="text" class="form-control" placeholder="Введите сумму выше последней ставки">
                            </div>
                        </div>
                    </form>
                </div>
                
                <div class="modal-footer">
                    <form class="form-horizontal" role="form">
                        <button type="button" class="btn btn-default" data-dismiss="modal">
                            <span class="glyphicon glyphicon-remove"></span>	Закрыть</button>
                        <button type="submit" class="btn btn-success">
                            <span class="glyphicon glyphicon-ok"></span>	Сделать ставку</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal СДЕЛАТЬ СТАВКУ-->


</div> <!-- /container -->