<div class="sign-in-form-wrap">
    <form class="form-horizontal" role="form" id="logInPage">
        <div class="form-group">
            <label class="col-sm-3">Ваш логин </label>
            <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email" name="email">
        </div>
        <div class="form-group">
            <label class="col-sm-3">Ваш пароль </label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Пароль" name="password">
        </div>

        <div class="checkbox">
            <label>
                <input type="checkbox"> Check me out
            </label>
        </div>
        <input type="submit" class="btn btn-success" value="Войти">
    </form>
</div>
<link rel="stylesheet" href="css/sign_in.css">