<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/admin.css">
    <title>Панель Администратора</title>
</head>
<body>
<div class="container">
    <div class="page-header">
        <h2>Панель Администратора</h2>
    </div>
<div class="row">
    <form action="" class="form-control-static col-md-6 col-md-offset-3" method="POST">
        <div class="form-group">
            <label for="admin_reg_login">Login</label>
            <input id="admin_reg_login" type="text" class="form-control" placeholder="login" name="admlog">
        </div>
        <div class="form-group">
            <label for="admin_reg_pass">Password</label>
            <input id="admin_reg_pass" type="password" class="form-control" placeholder="password" name="admpass">
        </div>
        <input type="submit" class="btn btn-block btn-info" value="Вход">
    </form>
</div>
</div>
<script src="/js/jquery.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/admin.js"></script>
</body>
</html>