 <!--PANEL-->
        <div class="class=panel panel-primary  col-md-9">
            <div class="panel-heading">
                <h3>Настройки сайта</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                <form action="" class="col-md-6">
                    <h3>Добавить администратора</h3>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                    </div>
                        <a href="" class="btn btn-success">Добавить</a>
                </form>
                <form action="" class="col-md-6">
                    <h3>Удалить администратора</h3>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Email address</label>
                            <select name="" id="" class="form-control">
                                <option value="">name</option>
                                <option value="">name</option>
                                <option value="">name</option>
                                <option value="">name</option>
                            </select>
                        </div>
                    <a href="" class="btn btn-danger">Удалить</a>
                </form>
                </div>
                <hr>
                <div class="row">
            <form action="" class="col-md-6">
                <h3>Добавить Катигорию</h3>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
                </div>
                <a href="" class="btn btn-success">Добавить</a>
            </form>
            <form action="" class="col-md-6">
                <h3>Удалить Катигорию</h3>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <select name="" id="" class="form-control">
                        <option value="">name</option>
                        <option value="">name</option>
                        <option value="">name</option>
                        <option value="">name</option>
                    </select>
                </div>
                <a href="" class="btn btn-danger">Удалить</a>
            </form>
                </div>
                <hr>
        </div>
            </div>
        <!--END PANEL-->