 <!--PANEL-->
        <div class="class=panel panel-primary  col-md-9">
            <div class="panel-heading">
                <form class="form-inline">
                    <div class="form-group">
                        <label for="category">Сортировать по</label>
                        <select class="form-control">
                            <option>Имя</option>
                            <option>Дата</option>
                        </select>
                        <select class="form-control">
                            <option>Убыванию</option>
                            <option>Возростанию</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="page">Отображать записей</label>
                        <select class="form-control">
                            <option>10</option>
                            <option>25</option>
                            <option>50</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Применить</button>
                </form>
            </div>
            <div class="panel-body">
                <div class="well well-lg">
                    <div class="media-left">
                        <img src="http://cs623831.vk.me/v623831501/3a8f6/2t2pGLAU_vQ.jpg" alt="..." class="img-rounded">
                    </div>
                    <div class="media-body">
                        <ul class="list-unstyled">
                            <li><h4><a href="">Название лота</a></h4></li>
                            <li><a href="mailto:mail@example.com"><span class="glyphicon glyphicon-envelope"></span> mail@example.com</a></li>
                            <li><a href="tel:77777777"><span class="glyphicon glyphicon-phone"></span> 77777777</a></li>
                            <li><a href="#"><span class="glyphicon glyphicon-briefcase"></span> Лоты</a></li>
                            <li><a href="#"><span class="glyphicon glyphicon-usd"></span> Ставки</a></li>
                        </ul>
                    </div>
                    <hr>
                    <a href="#" class="btn btn-success">Написать ЛС</a>
                    <a href="#" class="btn btn-primary">Забанить</a>
                    <a href="#" class="btn btn-warning">Зброс пароля</a>
                    <a href="#" class="btn btn-danger">Удалить профиль</a>
                </div>

        </div>
        <!--END PANEL-->