 <!--PANEL-->
           <div class="class=panel panel-primary  col-md-9">
                <div class="panel-heading">
                  <form class="form-inline">
              <div class="form-group">
                <label for="category">Сортировать по</label>
                <select class="form-control">
                  <option>Имя</option>
                  <option>Дата</option>
                </select>
                <select class="form-control">
                  <option>Убыванию</option>
                  <option>Возростанию</option>
                </select>
              </div>
              <div class="form-group">
                <label for="page">Отображать записей</label>
                <select class="form-control">
                  <option>10</option>
                  <option>25</option>
                  <option>50</option>
                </select>
              </div>
              <button type="submit" class="btn btn-primary">Применить</button>
            </form>
                </div>
                <div class="panel-body">
                    <div class="well well-lg">
                        <h3><a href=""><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Заголовок письма администратору</a></h3>
                        <mark><a href="">Логин пользователя</a></mark><span class="admin_mail_span_data text-muted">dd-mm-yyyy</span>
                    </div>
                    <div class="well well-lg">
                        <h3><a href=""><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Заголовок письма администратору</a></h3>
                        <mark><a href="">Логин пользователя</a></mark><span class="admin_mail_span_data text-muted">dd-mm-yyyy</span>
                    </div>
                    <div class="well well-lg">
                        <h3><a href=""><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Заголовок письма администратору</a></h3>
                        <mark><a href="">Логин пользователя</a></mark><span class="admin_mail_span_data text-muted">dd-mm-yyyy</span>
                    </div>
                    <div class="well well-lg">
                        <h3><a href=""><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Заголовок письма администратору</a></h3>
                        <mark><a href="">Логин пользователя</a></mark><span class="admin_mail_span_data text-muted">dd-mm-yyyy</span>
                    </div>
                    <div class="well well-lg">
                        <h3><a href=""><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Заголовок письма администратору</a></h3>
                        <mark><a href="">Логин пользователя</a></mark><span class="admin_mail_span_data text-muted">dd-mm-yyyy</span>
                    </div>
                    <div class="well well-lg">
                        <h3><a href=""><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Заголовок письма администратору</a></h3>
                        <mark><a href="">Логин пользователя</a></mark><span class="admin_mail_span_data text-muted">dd-mm-yyyy</span>
                    </div>
                </div>
           </div>
           <!--END PANEL-->