<!--create by Pavel
modified design by sebastian 30.07.2015 12:00
сама структура не изменена
мелкие фиксы дизайна
профиксена ДИВная вёрстка-->

        <!--++Блок поиска++-->
<div class="container profile">
         <div class=" jumbotron profile">
            <h1>Категория {<?=$category?>}</h1>
            <hr>
            
            <form role="form" class="form container" id="searchGoodsForm">
                    <div class="form-group">
                        <div class="col-sm-10">
                            <input name="searchText" type="text" class="form-control" placeholder="Введите ключевое слово для поиска">    
                        </div>
                        <div class="col-sm-2">
                            <input class="btn btn-info" type="submit" value="Поиск">
                        </div>
                    </div><!-- /input-group -->
            </form>
    </div>
</div>




    </div>
    <!--++Блок вывод товаров++-->
<div class="container profile">
    <div class=" jumbotron profile">

        <div class="well">
            <?php
            if (count($products) > 0) {
                foreach ($products as $product) { ?>
                    <div class="lot-block">
                        <div class="panel-body">
                            <!--img class="lot-photo" src="/img/goods-desc.png"-->
                            <img class="lot-photo" src="/img/lotPhoto/<?=$product["front_img"];?>">
                            <h3 ><a href="/lots/info/<?=$product["id"];?>"><?=$product["title"];?></a></h3>
                            <p ><?= $product['description']?></p>
                            <ul class="list-unstyled">
                                <li><a href="mailto:<?= $product['email']?>"><span class="glyphicon glyphicon-envelope"></span> Связаться с продавцом</a></li>
                                <li><span class="glyphicon glyphicon-phone"></span> <?= $product['phone']?></li>
                                <li><p><span class="glyphicon glyphicon-usd"></span> Последняя ставка</p></li>
                            </ul>

                            <span class="glyphicon glyphicon-tags form-control-feedback"></span>
                            <input type="button" class="form-control btn btn-success" value="Сделать ставку" data-toggle="modal" data-target="#makeBidModal">

                        </div>
                    </div>
                <?php } } ?>
        </div>

            <!--++Блок paginator++-->
            <div class="paginator">
                <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <ul class="pagination">
                            <li><a href="#">&laquo;</a></li>

                            <?php for ($page= 1; $page <= $pages; $page++) { ?>
                                <li><a href="<?=$link . $page;?>"><?=$page;?></a></li>
                            <?php }?>

                            <li><a href="#">&raquo;</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--++Блок paginator++-->
        </div>
    </div>


<!-- Modal СДЕЛАТЬ СТАВКУ-->
    <div class="modal fade" id="makeBidModal" tabindex="-1" role="dialog" aria-labelledby="makeBidModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Осуществить ставку на лот //выбранный лот//</h4>
                </div>
                <div class="modal-body">

                    <ul class="list-unstyled">

                        <div class="list-group">
                            <a href="#" class="list-group-item">
                                <h4 class="list-group-item-heading">Ставка</h4>
                                <p class="list-group-item-text">Кто поставил</p>
                                <a href="#" class="list-group-item">
                                    <h4 class="list-group-item-heading">Ставка</h4>
                                    <p class="list-group-item-text">Кто поставил</p>
                                    <a href="#" class="list-group-item">
                                        <h4 class="list-group-item-heading">Ставка</h4>
                                        <p class="list-group-item-text">Кто поставил</p>
                                    </a>
                                    <a href="#" class="list-group-item active">
                                        <h4 class="list-group-item-heading">Последняя ставка</h4>
                                        <p class="list-group-item-text">Кто поставил</p>
                                    </a>
                        </div>
                    </ul>
                    <form class="form-horizontal" role="form">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Ваша ставка </label>
                            <div class="col-sm-10">
                                <input required type="text" class="form-control" placeholder="Введите сумму выше последней ставки">
                            </div>
                        </div>
                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">
                        <span class="glyphicon glyphicon-remove"></span>    Закрыть</button>
                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon-ok"></span>    Сделать ставку</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
    <!-- Modal СДЕЛАТЬ СТАВКУ-->